/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGatewayV2,
  IGatewayV2Interface,
} from "../../../contracts/AnonymousPropertyVotingV2Fixed.sol/IGatewayV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "requester",
        type: "address",
      },
    ],
    name: "isPublicDecryptAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "requester",
        type: "address",
      },
    ],
    name: "isRequestDecryptAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGatewayV2__factory {
  static readonly abi = _abi;
  static createInterface(): IGatewayV2Interface {
    return new utils.Interface(_abi) as IGatewayV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGatewayV2 {
    return new Contract(address, _abi, signerOrProvider) as IGatewayV2;
  }
}
