/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AnonymousPropertyVotingV2Fixed__factory } from "./AnonymousPropertyVotingV2Fixed__factory";
export { IGatewayV2__factory } from "./IGatewayV2__factory";
