/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as anonymousPropertyVotingV2Sol from "./AnonymousPropertyVotingV2.sol";
export type { anonymousPropertyVotingV2Sol };
import type * as anonymousPropertyVotingV2FixedSol from "./AnonymousPropertyVotingV2Fixed.sol";
export type { anonymousPropertyVotingV2FixedSol };
import type * as anonymousPropertyVotingV2FixedLiteSol from "./AnonymousPropertyVotingV2FixedLite.sol";
export type { anonymousPropertyVotingV2FixedLiteSol };
import type * as gasOptimizedSol from "./GasOptimized.sol";
export type { gasOptimizedSol };
export type { AnonymousPropertyVoting } from "./AnonymousPropertyVoting";
export type { AnonymousPropertyVotingFixed } from "./AnonymousPropertyVotingFixed";
