/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AnonymousPropertyVotingV2Fixed } from "./AnonymousPropertyVotingV2Fixed";
export type { IGatewayV2 } from "./IGatewayV2";
