/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IInputVerifier,
  IInputVerifierInterface,
} from "../../../../../@fhevm/solidity/lib/Impl.sol/IInputVerifier";

const _abi = [
  {
    inputs: [],
    name: "cleanTransientStorage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IInputVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IInputVerifierInterface {
    return new utils.Interface(_abi) as IInputVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInputVerifier {
    return new Contract(address, _abi, signerOrProvider) as IInputVerifier;
  }
}
