# Codecov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 90%
        threshold: 2%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        target: 85%
        threshold: 5%
        if_no_uploads: error

    changes:
      default:
        if_no_uploads: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "node_modules"
  - "test"
  - "scripts"
  - "*.config.js"
  - "*.config.ts"
  - "coverage"
  - ".github"

flags:
  unittests:
    paths:
      - contracts/
    carryforward: true

github_checks:
  annotations: true

