/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface IDecryptionOracleInterface extends utils.Interface {
  functions: {
    "requestDecryption(uint256,bytes32[],bytes4)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "requestDecryption"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "requestDecryption",
    values: [BigNumberish, BytesLike[], BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "requestDecryption",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IDecryptionOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDecryptionOracleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    requestDecryption(
      requestID: BigNumberish,
      ctsHandles: BytesLike[],
      callbackSelector: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  requestDecryption(
    requestID: BigNumberish,
    ctsHandles: BytesLike[],
    callbackSelector: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    requestDecryption(
      requestID: BigNumberish,
      ctsHandles: BytesLike[],
      callbackSelector: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    requestDecryption(
      requestID: BigNumberish,
      ctsHandles: BytesLike[],
      callbackSelector: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    requestDecryption(
      requestID: BigNumberish,
      ctsHandles: BytesLike[],
      callbackSelector: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
