/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface IKMSVerifierInterface extends utils.Interface {
  functions: {
    "verifyDecryptionEIP712KMSSignatures(bytes32[],bytes,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "verifyDecryptionEIP712KMSSignatures"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verifyDecryptionEIP712KMSSignatures",
    values: [BytesLike[], BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyDecryptionEIP712KMSSignatures",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IKMSVerifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IKMSVerifierInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    verifyDecryptionEIP712KMSSignatures(
      handlesList: BytesLike[],
      decryptedResult: BytesLike,
      decryptionProof: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  verifyDecryptionEIP712KMSSignatures(
    handlesList: BytesLike[],
    decryptedResult: BytesLike,
    decryptionProof: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    verifyDecryptionEIP712KMSSignatures(
      handlesList: BytesLike[],
      decryptedResult: BytesLike,
      decryptionProof: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    verifyDecryptionEIP712KMSSignatures(
      handlesList: BytesLike[],
      decryptedResult: BytesLike,
      decryptionProof: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    verifyDecryptionEIP712KMSSignatures(
      handlesList: BytesLike[],
      decryptedResult: BytesLike,
      decryptionProof: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
