/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface DoSProtectionInterface extends utils.Interface {
  functions: {
    "getRemainingActions(address)": FunctionFragment;
    "getResetTime(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getRemainingActions" | "getResetTime"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getRemainingActions",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getResetTime",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRemainingActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResetTime",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DoSProtection extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DoSProtectionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getRemainingActions(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getResetTime(user: string, overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  getRemainingActions(
    user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getResetTime(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    getRemainingActions(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getResetTime(user: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getRemainingActions(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getResetTime(user: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getRemainingActions(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getResetTime(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
