/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface StorageOptimizerInterface extends utils.Interface {
  functions: {
    "efficientArrayOperation(uint256[])": FunctionFragment;
    "getFlag(uint8)": FunctionFragment;
    "setFlag(uint8,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "efficientArrayOperation" | "getFlag" | "setFlag"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "efficientArrayOperation",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getFlag",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFlag",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "efficientArrayOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFlag", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFlag", data: BytesLike): Result;

  events: {};
}

export interface StorageOptimizer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StorageOptimizerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    efficientArrayOperation(
      data: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { sum: BigNumber }>;

    getFlag(
      flagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setFlag(
      flagIndex: BigNumberish,
      value: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  efficientArrayOperation(
    data: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFlag(flagIndex: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  setFlag(
    flagIndex: BigNumberish,
    value: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    efficientArrayOperation(
      data: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFlag(
      flagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setFlag(
      flagIndex: BigNumberish,
      value: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    efficientArrayOperation(
      data: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFlag(
      flagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFlag(
      flagIndex: BigNumberish,
      value: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    efficientArrayOperation(
      data: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFlag(
      flagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFlag(
      flagIndex: BigNumberish,
      value: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
