/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AnonymousPropertyVotingV2FixedLite__factory } from "./AnonymousPropertyVotingV2FixedLite__factory";
export { IGatewayV2__factory } from "./IGatewayV2__factory";
