/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AnonymousPropertyVotingV2 } from "./AnonymousPropertyVotingV2";
export type { IGatewayV2 } from "./IGatewayV2";
