/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface IGatewayV2Interface extends utils.Interface {
  functions: {
    "isRequestDecryptAllowed(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "isRequestDecryptAllowed"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isRequestDecryptAllowed",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "isRequestDecryptAllowed",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IGatewayV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IGatewayV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isRequestDecryptAllowed(
      requester: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  isRequestDecryptAllowed(
    requester: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    isRequestDecryptAllowed(
      requester: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    isRequestDecryptAllowed(
      requester: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isRequestDecryptAllowed(
      requester: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
