/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AnonymousPropertyVotingV2FixedLite } from "./AnonymousPropertyVotingV2FixedLite";
export type { IGatewayV2 } from "./IGatewayV2";
