/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  DoSProtection,
  DoSProtectionInterface,
} from "../../../contracts/GasOptimized.sol/DoSProtection";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "remainingTime",
        type: "uint256",
      },
    ],
    name: "CooldownNotElapsed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "actionsUsed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxActions",
        type: "uint256",
      },
    ],
    name: "RateLimitExceeded",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getRemainingActions",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getResetTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class DoSProtection__factory {
  static readonly abi = _abi;
  static createInterface(): DoSProtectionInterface {
    return new utils.Interface(_abi) as DoSProtectionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DoSProtection {
    return new Contract(address, _abi, signerOrProvider) as DoSProtection;
  }
}
