/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  GasOptimized,
  GasOptimizedInterface,
} from "../../../contracts/GasOptimized.sol/GasOptimized";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "size",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxSize",
        type: "uint256",
      },
    ],
    name: "BatchSizeTooLarge",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "required",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "available",
        type: "uint256",
      },
    ],
    name: "GasLimitExceeded",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212201b162922d6a774f010efc9559b39fde64cdf55b655c10f15a34a19359026bfc064736f6c63430008180033";

type GasOptimizedConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GasOptimizedConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GasOptimized__factory extends ContractFactory {
  constructor(...args: GasOptimizedConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<GasOptimized> {
    return super.deploy(overrides || {}) as Promise<GasOptimized>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): GasOptimized {
    return super.attach(address) as GasOptimized;
  }
  override connect(signer: Signer): GasOptimized__factory {
    return super.connect(signer) as GasOptimized__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GasOptimizedInterface {
    return new utils.Interface(_abi) as GasOptimizedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GasOptimized {
    return new Contract(address, _abi, signerOrProvider) as GasOptimized;
  }
}
